version: "3.7"
services:
  backend:
    build:
      context: ..
      dockerfile: ./services/backend/Dockerfile
      args:
        ENV: development
    expose:
      - 3000
    restart: always
    env_file:
      - ../.env

  frontend:
    depends_on:
      - backend
    build:
      context: ..
      dockerfile: ./services/frontend/Dockerfile
    expose:
      - 8080
    restart: always
    env_file:
      - ../.env

  proxy:
    image: nginx
    depends_on:
      - backend
      # - frontend
    volumes:
      - ../nginx/templates:/etc/nginx/templates
    ports:
      - 80:80
    restart: always
    env_file:
      - ../.env
